timezone: Europe/Berlin

title: Proxer-Devblog
author:
  name: Proxer-Admin
  email: "support@proxer.de"

description: >-
  Proxer.me Devblog
baseurl: ""
url: "https://proxerdev.github.io"

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed

remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%d.%m.%Y %H:%M"